aliyun-oss:
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  endpoint: yourEndpoint
autocode:
  root: ""
  server: /server
  server-api: /api/v1
  server-initialize: /initialize
  server-model: /model
  server-request: /model/request/
  server-router: /router
  server-service: /service
  web: /web/src
  web-api: /api
  web-flow: /view
  web-form: /view
  web-table: /view
captcha:
  img-height: 80
  img-width: 240
  key-long: 6
casbin:
  model-path: ./resource/rbac_model.conf
email:
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  nickname: test
  port: 465
  secret: xxx
  to: xxx@qq.com
excel:
  dir: ./resource/excel/
jwt:
  buffer-time: 86400
  expires-time: 604800
  signing-key: qmPlus
local:
  path: uploads/file
mysql:
  config: ""
  db-name: ""
  log-mode: false
  log-zap: ""
  max-idle-conns: 10
  max-open-conns: 100
  password: ""
  path: ""
  username: ""
postgresql:
  config: sslmode=disable TimeZone=Asia/Shanghai
  db-name: dddd
  host: 127.0.0.1
  logger: false
  max-idle-conns: 10
  max-open-conns: 10
  password: dddd
  port: 5432
  prefer-simple-protocol: true
  username: dddd
qiniu:
  access-key: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  bucket: qm-plus-img
  img-path: http://qmplusimg.henrongyi.top
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
  use-cdn-domains: false
  use-https: false
  zone: ZoneHuadong
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
system:
  addr: 8888
  db-type: postgres
  env: public
  oss-type: local
  use-multipoint: false
tencent-cos:
  base-url: https://gin.vue.admin
  bucket: xxxxx-10005608
  path-prefix: gin-vue-admin
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
zap:
  director: log
  encode-level: LowercaseColorLevelEncoder
  format: console
  level: info
  link-name: latest_log
  log-in-console: true
  prefix: '[GIN-VUE-ADMIN]'
  show-line: true
  stacktrace-key: stacktrace
